# database: "mysql://user:secret_pasword@tcp(127.0.0.1:3306)/rest_api?charset=utf8mb4&parseTime=True&loc=Local"

# database: user:secretpasword@tcp(127.0.0.1:3306)/api?charset=utf8mb4&parseTime=True&loc=Local'

# server:
#   address: 8080


# auth:
#   hash_salt: "hash_salt"
#   signing_key: "signing_key"
#   token_ttl: 86400